 export const cakes = [
  {
    id: '1',
    name: 'Chocolate Cake',
    description: 'Rich and creamy chocolate delight.',
    price: '$10',
    image: require('../../../assets/Images/cake1.png'),
  },
  {
    id: '2',
    name: 'Vanilla Cake',
    description: 'Classic vanilla cake with a smooth texture.',
    price: '$12',
    image: require('../../../assets/Images/cake2.png'),
  },
  {
    id: '3',
    name: 'Strawberry Cake',
    description: 'Fresh strawberry cake with cream layers.',
    price: '$15',
    image: require('../../../assets/Images/cake3.png'),
  },
  {
    id: '4',
    name: 'Red Velvet Cake',
    description: 'Soft and moist red velvet goodness.',
    price: '$18',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '5',
    name: 'Black Forest Cake',
    description: 'Chocolate cake with cherries and whipped cream.',
    price: '$14',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '6',
    name: 'Blueberry Cheesecake',
    description: 'Creamy cheesecake with fresh blueberry topping.',
    price: '$20',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '7',
    name: 'Carrot Cake',
    description: 'Moist cake with carrots, nuts, and cream cheese frosting.',
    price: '$13',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '8',
    name: 'Lemon Drizzle Cake',
    description: 'Tangy lemon cake with a sweet glaze.',
    price: '$11',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '9',
    name: 'Coffee Cake',
    description: 'Rich coffee-flavored sponge with cinnamon crumble.',
    price: '$16',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '10',
    name: 'Tiramisu',
    description: 'Classic Italian dessert with layers of coffee-soaked sponge.',
    price: '$22',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '11',
    name: 'Pineapple Upside-Down Cake',
    description: 'Buttery cake with caramelized pineapple topping.',
    price: '$15',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '12',
    name: 'Raspberry Almond Cake',
    description: 'Soft almond sponge with fresh raspberries.',
    price: '$18',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '13',
    name: 'Coconut Cake',
    description: 'Light coconut-flavored sponge with coconut flakes.',
    price: '$17',
    image: require('../../../assets/Images/cake4.png'),
  },
  {
    id: '14',
    name: 'Mango Mousse Cake',
    description: 'Soft mango sponge with creamy mousse layers.',
    price: '$19',
    image: require('../../../assets/Images/cake4.png'),
  },
];
